spring.application.name=mobilemoney

# CONFIGURATION DU PORT DE L'APPLICATION
server.port=8083

# CONFIGURATION DE LA BASE DE DONNEES (WAMP/MYSQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mobilemoney
spring.datasource.username=root
spring.datasource.password=

# CONFIGURATION JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURATION THYMELEAF
spring.thymeleaf.cache=false